### ISSUE TITLE
Example uses retired Ubuntu 16 and deprecated Ubuntu 18 runner

### ISSUE THREAD

**Issue by MikeMcC399** [bahmutov/cypress-gh-action-example#68]
## Problem description

[.github/workflows/ubuntu.yml](https://github.com/bahmutov/cypress-gh-action-example/blob/master/.github/workflows/ubuntu.yml) which uses:

- ubuntu-16.04
- ubuntu-18.04

fails to run. See for example run [2216393814](https://github.com/bahmutov/cypress-gh-action-example/actions/runs/2216393814) showing `ubuntu-16` failing.

The currently supported list of [GitHub runner-images](https://github.com/actions/runner-images) shows:

| Image                              | YAML Label                        |
| ---------------------------------- | --------------------------------- |
| Ubuntu 22.04                       | `ubuntu-latest` or `ubuntu-22.04` |
| Ubuntu 20.04                       | `ubuntu-20.04`                    |
| Ubuntu 18.04 <sup>deprecated</sup> | `ubuntu-18.04`                    |

Ubuntu 16.04 was removed from the available runners on September 20, 2021. (See https://github.com/actions/runner-images/issues/.)

## Suggested fix

Update [.github/workflows/ubuntu.yml](https://github.com/bahmutov/cypress-gh-action-example/blob/master/.github/workflows/ubuntu.yml):

Remove

- ubuntu-16.04
- ubuntu-18.04

and replace with

- ubuntu-20.04
- ubuntu-22.04

**Comment by MikeMcC399** [comment]
- PR https://github.com/bahmutov/cypress-gh-action-example/pull/69 is submitted to resolve this issue

**Comment by bahmutov** [comment]
Done
