### ISSUE TITLE
How do you use Cypress with CodeceptJS?

### ISSUE THREAD

**Issue by bionicles** [bahmutov/cypress-gh-action-example#9]
Would it be possible to please add an action which would support the CodeceptJS syntax? It is much simpler to write, read, and maintain

**Comment by bahmutov** [comment]
I am not sure what you mean. Can you provide examples with links?

**Comment by bionicles** [comment]
Absolutely. Right now you write Cypress tests like this:

```
describe('Form Interactions', function () {
  beforeEach(function () {
    cy.viewport(400, 300)
    cy.visit('/index.html')
  })

  it('updates range value when moving slider', function () {
    // To interact with a range input (slider), we need to set its value and
    // then trigger the appropriate event to signal it has changed

    // Here, we invoke jQuery's val() method to set the value
    // and trigger the 'change' event

    // Note that some implementations may rely on the 'input' event,
    // which is fired as a user moves the slider, but is not supported
    // by some browsers
    cy.get('input[type=range]').as('range')
    .invoke('val', 25)
    .trigger('change')

    cy.get('@range').siblings('p')
    .should('have.text', '25')
  })
})
```

It would be extremely cool for faster progress + easier maintenance if we could write CodeceptJS tests like this:

```
Feature('CodeceptJS demo');

Scenario('login with generated password', async (I) => {
  I.fillField('email', 'miles@davis.com');
  I.click('Generate Password');
  const password = await I.grabTextFrom('#password');
  I.click('Login');
  I.fillField('email', 'miles@davis.com');
  I.fillField('password', password);
  I.click('Log in!');
  I.see('Hello, Miles');
});
```

This being so easy to read, would accelerate the process of designing, writing, using updating tests

https://codecept.io/basics/

**Comment by bionicles** [comment]
relevant: https://github.community/t5/GitHub-Actions/How-do-you-matrix-test-a-website-on-mobile-browsers-and-screen/m-p/43418/highlight/false#M5376

**Comment by bionicles** [comment]
here's an issue on CodeceptJS repo and they do have Cypress on their roadmap  https://github.com/Codeception/CodeceptJS/issues/2142

 might take momentum from multiple angles to add this but it would be fun to write tests like that

**Comment by jennifer-shehane** [comment]
@bionicles Found where CodeceptJS has Cypress on their roadmap here: https://github.com/Codeception/CodeceptJS/wiki/Roadmap. 

Without CodeceptJS syntax supporting Cypress, I'm not seeing how this is related to our GitHub Actions repo at the moment with the basics of the syntax not functionally working. CodeceptJS will need to support integration with Cypress first or someone would need to create a plugin in Cypress to allow CodeceptJS syntax. https://docs.cypress.io/api/plugins/writing-a-plugin.html

**Comment by bahmutov** [comment]
I agree with @jennifer-shehane - @bionicles I am not sure that having `await` syntax is an improvement over Cypress command chains, so we don't plan to natively support it or provide examples any time soon.
